config/routes.rb
Rails.application.routes.draw do
  resources :rates
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rate.rb
class Rate < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: [:show, :edit, :update, :destroy]

  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(rate_params)

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'Rate was successfully created.' }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { render :new }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1
  # PATCH/PUT /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate.destroy
    respond_to do |format|
      format.html { redirect_to rates_url, notice: 'Rate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rate_params
      params.require(:rate).permit(:loves, :likes, :song)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Return logged-in user, if they exist
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Check if user is logged in
  def logged_in?
    !current_user.nil?
  end

  # Logs out user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def teacher?
    current_user.isTeacher
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
 <small>
   Rate your favorite songs from Taylor Swift's newest Album, Evermore!
</small>
<nav>
  <ul>
    <li>© Taylor Swift Fandom</li>
  </ul>
 </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
  <%= link_to "Evermore", root_path, id: "logo" %>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item"><%= link_to "Rate Now!", rates_path %></li>
    </ul>
  </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container"> 
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/rates/_form.html.erb
<%= form_with(model: rate, local: true) do |form| %>
  <% if rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
        <% rate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :loves %>
    <%= form.number_field :loves %>
  </div>

  <div class="field">
    <%= form.label :likes %>
    <%= form.number_field :likes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<h1>Editing Rate</h1>

<%= render 'form', rate: @rate %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

app/views/rates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Evermore</h1>

<table>
  <thead>
    <tr>
      <th>Loves</th>
      <th>Likes</th>
      <th>Song</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rates.each do |rate| %>
      <tr>
        <td><%= rate.loves %></td>
        <td><%= rate.likes %></td>
        <td><%= rate.song %></td>
        <td><%= link_to 'Love', edit_rate_path(rate) %></td>
        <td><%= link_to 'Like', edit_rate_path(rate)  %></td>
        <td><%= link_to 'Show', rate %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/rates/new.html.erb
<h1>New Rate</h1>

<%= render 'form', rate: @rate %>

<%= link_to 'Back', rates_path %>

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Loves:</strong>
  <%= @rate.loves %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @rate.likes %>
</p>

<p>
  <strong>Song:</strong>
  <%= @rate.song %>
</p>

<%= link_to 'Back', rates_path %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Evaluate') %>
<div class="center jumbotron">

<h1>
  Evermore
</h1>

<h2>
  by Taylor Swift
</h2>


<img src="/assets/TS.png" alt="Evaluate logo" class="img-fluid">

<h2>
  Click the link below to rate your favorite new songs!
</h2>
  
  <%= link_to "Rate Now!", rates_path, class: "btn btn-lg btn-primary" %>
  
</div>